### ISSUE TITLE
`presence.getAll()` returns null for previous client connections

### ISSUE THREAD

**Issue by apkostka** [deepstreamIO/deepstream.io-website#13]
Using 4.2.2 deepstream docker image with docker-compose, a 4.x client querying presence, and a 2.3.0 client logging in.

Client logs in with a username:
```
ds.login({ type: 'webhook', username: device_id }, (success, data) => { ...
```

Which does trigger a response from `ds.presence.subscribe(device_id, (dev, login) => {...`

However, if the client logs in, then deepstream (the docker container) is restarted, the initial call for `getAll()` returns null instead of an object:
```
ds.presence.getAll([device_id], (connections) => { ...
```

**Comment by yasserf** [comment]
hey! can you please raise a PR against the website for this?

**Comment by apkostka** [comment]
PR is here: https://github.com/deepstreamIO/deepstream.io-website/pull/16
