### ISSUE TITLE
Slack link is broken

### ISSUE THREAD

**Issue by viridia** [deepstreamIO/deepstream.io-website#143]
I'm trying to get in touch with someone at deepstream. I notice that the slack link (on the 'info' page) leads to a broken page on heroku. I also tried email, but got no response. I don't use social media, so twitter / facebook are out. Seems like there's no other way to contact except for filing bugs on GitHub.

**Comment by viridia** [comment]
ping?

**Comment by yasserf** [comment]
hello!

Sorry for not seeing this earlier. Both slack links are working normally (just tried them out). Would you mind sending me a link? Or, in the case of extremely intense caching, clear your cache?

Cheers,
Yasser

**Comment by viridia** [comment]
Yes, I just tried it and it still is not working for me. The link is located on the page:

https://deepstream.io/info/community/get-in-touch/

And the actual linked location is:

https://deepstream-slack.herokuapp.com/

When I click on the link it sends me to a blank page that has the message: 

> Application error
> An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.

**Comment by yasserf** [comment]
Perfect, we have multiple places where we mention slack and we apparently missed that one. 

https://deepstreamio-slack.herokuapp.com/

Thats the link, I have just pushed an update to the website and it should be live shorty. Thank you!

**Comment by viridia** [comment]
Thanks!

By the way, I tried locating the deepstream slack channel by other means and failed. Doing a Google search for "deepstream slack channel" yields search results on integrating deepstream and slack, but no results on getting access to the support channel.

**Comment by yasserf** [comment]
Interesting! We have a few new links we will be adding in the upcoming weeks that should hopefully bring the SEO index higher for that. Thanks for the headsup tho!
