### ISSUE TITLE
Webtask not accepting new account, replacement needed

### ISSUE THREAD

**Issue by dkotama** [deepstreamIO/deepstream.io-website#21]
according to [this](https://deepstream.io/tutorials/example-apps/live-progress-bar/) sample, registering to webtask is required,
but today (9 Oct) I found that webtask is not accepting new account

any idea for replacement?

**Comment by yasserf** [comment]
hey! So yeah the easiest thing to do would just be to run it yourself via express on your local machine. 

```
const Express = require('express');
const bodyParser = require('body-parser');
const app = Express();

app.use(bodyParser.urlencoded({ extended: false }))
app.use(bodyParser.json())

app.get('/', (req, res) => {
  res.json({text: 'hi'})
})

app.listen(9090) // any free port
```

And then just ping 'localhost:9090/post'

```
axios.post('localhost:9090/post', {}).then((res) => {
        console.log(res.data.status)
        this.resStatus = res.data.status
        setTimeout(() => {
          this.resValue = 0;
          this.resStatus = 'Post to Server'
          this.disabled = false
        }, 2000)
```

**Comment by yasserf** [comment]
If that works if you can update the tutorial it would be amazing 😁

```
https://github.com/deepstreamIO/deepstream.io-website/blob/master/content/tutorials/40-example-apps/live-progress-bar/index.md
```

**Comment by yasserf** [comment]
Actually turning this into a guide so no worries about editing it 😁

**Comment by yasserf** [comment]
This has been turned into a guide using express, currently on staging.deepstream.io
