### ISSUE TITLE
tutorial: how to use deepstream with angular2

### ISSUE THREAD

**Issue by yasserf** [deepstreamIO/deepstream.io-website#28]
Deliverables:
1) An angular2 app under : deepstreamIO/ds-demo-simple-app-angular2
2) A tutorial on how to use it

Thanks for raising this @gmchaturvedi1

If anyone wants to create the identical feature set as angular1 for angular2 please let us know, angular two requires a bit of a.. background. More than happy to help out if anyone wants to pick this up!

**Comment by damiendube** [comment]
Insteam of a complete demo, could we just update the Intergation page with a specific angular2 example?

Similar to:
https://deepstream.io/tutorials/integrations/frontend-angular/

Most of what is explained in this page is not true for angular2. The use of Observables fixes most of the angular1 ruff edges.

**Comment by yasserf** [comment]
https://deepstreamhub.com/tutorials/getting-started/angular-2

Sorry for late reply on this one!
