### ISSUE TITLE
Broken link on permissions page

### ISSUE THREAD

**Issue by juanicotolengo** [deepstreamIO/deepstream.io-website#36]
Found a broken link here:
https://deepstream.io/tutorials/concepts/security/#permissioning
Which tries to redirect to here:
https://deepstream.io/tutorials/core/permission/conf-simple/
It returns a 404 error.

**Comment by jaime-ez** [comment]
Hi, thanks for raising this issue.
A fix has been pushed and it should be live on the next deploy.
