### ISSUE TITLE
Create a comparison page for different technologies

### ISSUE THREAD

**Issue by yasserf** [deepstreamIO/deepstream.io-website#37]
Acceptance criteria:
- Lives under info
- Compares against proprietary and open source technologies available from [the leggetter list](http://www.leggetter.co.uk/real-time-web-technologies-guide/).

Since quite a few libraries out there concentrate on on or two things, we will probably compare the technologies technologies separately for:

Connection Types
Messaging Protocol
How they scale
Compatibility with different databases/caches
realtime functionality ( data-sync / event / rpc )
...

Suggestions for comparison points would be great, will flesh them out accordingly.

**Comment by yasserf** [comment]
Added blogpost that covers competitors in high level detail

**Comment by lholznagel** [comment]
For all that are searching for the post like me, here is the Link: [Blog](https://deepstream.io/blog/realtime-framework-overview/)
