### ISSUE TITLE
document all client.presence methods

### ISSUE THREAD

**Issue by jaime-ez** [deepstreamIO/deepstream.io-website#47]

**Comment by yasserf** [comment]
which ones are missing from https://deepstream.io/docs/client-js/presence/?

**Comment by jaime-ez** [comment]
Hi, these:

https://github.com/deepstreamIO/deepstream.io-client-js/blob/master/src/presence/presence-handler.ts#L60
https://github.com/deepstreamIO/deepstream.io-client-js/blob/master/src/presence/presence-handler.ts#L126

It's not the method, but the possible method calls, I'll make a pull

**Comment by yasserf** [comment]
👍

**Comment by jaime-ez** [comment]
pushed
