### ISSUE TITLE
Broke on Firefox

### ISSUE THREAD

**Issue by Buom01** [deepstreamIO/deepstream.io-website#53]
Hi,

I noticed there are a small issue with the `width` of the documentation on Firefox (latest, 87.0 (64 bits)): The doc is shrunk to the left on 1/3 on the screen while it should be approx 3/4: https://ibb.co/TmtMj1c
(It seems to not happen on my Windows' Firefox)

I suggest to add `width: 100%;` to the following `div` elements which is displayed as `flex`:
https://github.com/deepstreamIO/deepstream.io-website/blame/73a75071a716479ad44e66827d014b547553c93f/src/components/Markdown/MarkdownContent/MarkDownContent.module.css#L2

After research I suppose that's a bug of Firefox: https://drafts.csswg.org/css-flexbox-1/#flex-containers
I primarily though that's were a miss but according to what I read on the draft it should react like a `display: block` while it act weirdly.

**Comment by jaime-ez** [comment]
thanks for raising. If you're interested on contributing please check the CI issue #51
