### ISSUE TITLE
662256000000 is not  21 years

### ISSUE THREAD

**Issue by Iiridayn** [deepstreamIO/deepstream.io-website#65]
In https://github.com/deepstreamIO/deepstream.io-website/blob/master/src/tutorials/core/permission-conf-advanced/readme.md some example code comments that "662256000000 = 21 years in milliseconds". This is false - `662256000000 = 21*365*24*60*60*1000`, which, first of all, does not account for leap years. Anyone using this code for the stated purpose would end up selling alcohol to minors. I'm using a bit of hyperbole here, to point out that date and time code are _not_ simple. I'm raising this as an issue because I'm not certain if the example should be fixed or replaced.

Correct code: `bd = new Date(user.data.birthdayTimestamp); return new Date(bd.getFullYear()+21, bd.getMonth(), bd.getDate(), bd.getHours(), bd.getMinutes()) < now` (hours and minutes are needed to keep timezones accurate). In my case, the offset ends up being 662688000000. Not sure how to convert that for `Valve` just yet.

Further reading (both are quick):
http://infiniteundo.com/post/25326999628/falsehoods-programmers-believe-about-time
http://infiniteundo.com/post/25509354022/more-falsehoods-programmers-believe-about-time

**Comment by yasserf** [comment]
Thanks Liridayn! Will change to an example that isn't date related to simplify things!

**Comment by Iiridayn** [comment]
Capital "i", not L :).

2016-10-10 3:04 GMT-06:00 Yasser Fadl <notifications@github.com>:

**Comment by yasserf** [comment]
My bad =)
