### ISSUE TITLE
Clarifying deepstream.io project status

### ISSUE THREAD

**Issue by stemuk** [deepstreamIO/deepstream.io-website#7]
Hey!
So first of all thanks a lot for the great v4 update, I waited a long time for this and I am pumped to see deepstream back in action! I would love to hear a small update however on the general status of the project, since the last information I got in 2017 was that deepstreamHub (the company) was shutting down. What I am curious about is whether deepstream.io is now continued as a community project and (if so), what possible ways of contributing for the community are. I am truly sorry if this has already been posted somewhere else, but it would be really interesting to get a general outline of this projects future. 
Thanks again for breathing new life into deepstream.io!

**Comment by yasserf** [comment]
hey!

Your welcome!

The deepstreamHub platform has shut down. Currently this means that we still offer enterprise solutions and open-source. In V3 there was a bigger chasm between enterprise and OS, where enterprise was a separate binary. In V4 the clustering and monitoring logic is now deployed via enterprise plugins, which means that alot of the work that goes into deepstream is now immediately benefiting the OS, as there is no longer a separate 'trunk'.

Generally I'm extremely fortunate to be working tightly with some of the techs users, so alot of the work is around trying to make deepstream work with their needs and fixing any issues they find.

Once I get a V3 compatibility layer working for clients I will be taking down most the documentation from deepstreamHub and forwarding it onto deepstream.io

As for community help, whatever you see fit! Generally the thing this project needs most as always is publicity.

- writing a cook book
- writing a plugin
- writing an endpoint
- writing an adaptor for a database
- writing a small demo that uses it

For anyone willing to take on a massive task, if you have some skills in other languages writing an SDK would amazing, but they require alot of work! Sort of need a bigger community to help build out docs on how to go forward with that, which goes back to publicity.

Hope that helps!
