### ISSUE TITLE
Confusing ASCII character description

### ISSUE THREAD

**Issue by rudilee** [deepstreamIO/deepstream.io-website#71]
On the page: https://deepstream.io/info/protocol/message-structure-overview/

Which describing ASCII character of (30) as "record separator" and (31) as "group separator"
When i lookup the ASCII table (31) is actually "unit separator", and "group separator" is (29)
And there's typo for: .."group seperator".. which suppose to be: .."group separator"..

**Comment by rudilee** [comment]
If it's actually a mistake, i'm committing fixes in #72

**Comment by AlexBHarley** [comment]
Thanks for that, makes perfect sense. I'll run it by the rest of the team first

**Comment by yasserf** [comment]
Merged, thanks again @rudilee

**Comment by rudilee** [comment]
Your welcome, glad to help a bit :smile:
