### ISSUE TITLE
You seem to be loss

### ISSUE THREAD

**Issue by danikk741** [deepstreamIO/deepstream.io-website#9]
tried to open https://deepstream.io/tutorials/custom-plugins/an-overview/storage, but got 'You seem to be lost!' page

**Comment by yasserf** [comment]
thanks for raising! appears a link is incorrect

for now you can see it here:

https://deepstream.io/tutorials/custom-plugins/storage/index.html

**Comment by jaime-ez** [comment]
This seems to be already fixed.
